INIT_POPULATION_SIZE = 10
MUTATION_RATE = 0.3
NUM_GENERATIONS_SIMULATED = 10
NUM_TRAITS = 5 # size, stamina, strength, speed, smartness

# rendering constants
SCREEN_WIDTH = 1400
SCREEN_HEIGHT = 800
FPS = 60
RADIUS = 20

SIM_SPEED = 10
DAYS_IN_YEAR = 100